import { Carro } from '../models/carro.model';

export const carros: Carro[] = [
  {
    id: 1,
    name: 'Partner',
    year: '2016',
    type: 'Utilitário',
    engine: '1.6',
    size: '2',
    imgPath: 'assets/Carros/Partner.png',
  },
  {
    id: 2,
    name: 'Fiorino',
    year: '2017',
    type: 'Utilitário leve',
    engine: '1.6',
    size: '2',
    imgPath: 'assets/Carros/Fiorino.png',
  },
  {
    id: 3,
    name: 'Doblo',
    year: '2018',
    type: 'Minivan',
    engine: '1.8',
    size: '7',
    imgPath: 'assets/Carros/Doblo.png',
  },
  {
    id: 4,
    name: 'Toro',
    year: '2016',
    type: 'Picape média',
    engine: '1.6',
    size: '5',
    imgPath: 'assets/Carros/Toro.png',
  },
  {
    id: 5,
    name: 'Ford Ká',
    year: '2019',
    type: 'Sedan Compacto',
    engine: '1.0',
    size: '5',
    imgPath: 'assets/Carros/Ford Ká.png',
  },
  {
    id: 6,
    name: 'Versa',
    year: '2019',
    type: 'Sedan médio',
    engine: '1.4',
    size: '5',
    imgPath: 'assets/Carros/Versa.png',
  },
  {
    id: 7,
    name: 'Jetta',
    year: '2021',
    type: 'Sedan grande',
    engine: '2.0',
    size: '5',
    imgPath: 'assets/Carros/Jetta.png',
  },
  {
    id: 8,
    name: 'Saveiro',
    year: '2018',
    type: 'Picape leve-média',
    engine: '1.6',
    size: '5',
    imgPath: 'assets/Carros/Saveiro.png',
  },
  {
    id: 9,
    name: 'Strada',
    year: '2016',
    type: 'Picape leve',
    engine: '1.4',
    size: '2',
    imgPath: 'assets/Carros/Strada.png',
  },
  {
    id: 10,
    name: 'Camaro',
    year: '2017',
    type: 'Coupé',
    engine: '2.0',
    size: '4',
    imgPath: 'assets/Carros/Camaro.png',
  },
  {
    id: 11,
    name: 'T-Cross',
    year: '2020',
    type: 'Crossover',
    engine: '1.6',
    size: '5',
    imgPath: 'assets/Carros/T-Cros.png',
  },
  {
    id: 12,
    name: 'Tiggo 8',
    year: '2021',
    type: 'SUV Grande',
    engine: '2.0',
    size: '7',
    imgPath: 'assets/Carros/Tiggo 8.png',
  },
  {
    id: 13,
    name: 'Ford Ká',
    year: '2017',
    type: 'Hatch médio',
    engine: '1.0',
    size: '5',
    imgPath: 'assets/Carros/Ford Ká - 2017.png',
  },
  {
    id: 14,
    name: 'Duster',
    year: '2020',
    type: 'SUV Compacta',
    engine: '1.6',
    size: '5',
    imgPath: 'assets/Carros/Duster.png',
  },
  {
    id: 15,
    name: 'Mini Cooper',
    year: '2021',
    type: 'Hatch compacto',
    engine: '1.8',
    size: '5',
    imgPath: 'assets/Carros/Cooper.png',
  },
  {
    id: 16,
    name: 'Jeep Compas',
    year: '2021',
    type: 'SUV Médio',
    engine: '1.8',
    size: '7',
    imgPath: 'assets/Carros/Compas.png',
  },
];
